// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROJECTO_FINAL_YENSI.DAL;

namespace PROJECTO_FINAL_YENSI.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20201210195313_Migracion1")]
    partial class Migracion1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("PROJECTO_FINAL_YENSI.Entidades.Cliente", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cedula")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PROJECTO_FINAL_YENSI.Entidades.Habitacion", b =>
                {
                    b.Property<int>("HabitacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("HabitacionID");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("PROJECTO_FINAL_YENSI.Entidades.Hotel", b =>
                {
                    b.Property<int>("HotelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreHotel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("HotelID");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("PROJECTO_FINAL_YENSI.Entidades.Reservacion", b =>
                {
                    b.Property<int>("ReservacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hotel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservacionID");

                    b.ToTable("Reservaciones");
                });

            modelBuilder.Entity("PROJECTO_FINAL_YENSI.Entidades.ReservacionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HabitacionID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservacionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TiempoDeReserva")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReservacionID");

                    b.ToTable("ReservacionDetalle");
                });

            modelBuilder.Entity("PROJECTO_FINAL_YENSI.Entidades.TipoHabitacion", b =>
                {
                    b.Property<int>("TipoHabitacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("TipoHabitacionID");

                    b.ToTable("tipoHabitaciones");
                });

            modelBuilder.Entity("PROJECTO_FINAL_YENSI.Entidades.TipoUsuario", b =>
                {
                    b.Property<int>("TipoUsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("TipoUsuarioID");

                    b.ToTable("tipoUsuarios");
                });

            modelBuilder.Entity("PROJECTO_FINAL_YENSI.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassWord")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoUsuario")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("PROJECTO_FINAL_YENSI.Entidades.ReservacionDetalle", b =>
                {
                    b.HasOne("PROJECTO_FINAL_YENSI.Entidades.Reservacion", null)
                        .WithMany("reservacionDetalle")
                        .HasForeignKey("ReservacionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PROJECTO_FINAL_YENSI.Entidades.Reservacion", b =>
                {
                    b.Navigation("reservacionDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
